package com.service.enums;

public enum DocumentType {
	DPI_FRONT,
	DPI_BACK,
	SELFIE,
	PENAL_RECORD,
	POLICE_RECORD,
	LICENSE,
	CIRCULATION_CARD,
	INSURANCE,
	VEHICLE_PHOTO,
	ACADEMIC_DEGREE,
	TECHNICAL_CERTIFICATE,
	COURSE_CERTIFICATE,
	PROFESSIONAL_LICENSE,
	ADDRESS_PROOF
}
