package com.service.enums;

public enum ProfileStatus {
	  PENDING_PROFILE_INFO,
	  PENDING_ID_VERIFICATION, 
	  PENDING_BACKGROUND_CHECK, 
	  PENDING_DOCUMENT_UPLOAD, 
	  PENDING_CONTRACT_SIGNATURE, 
	  PENDING_REVIEW, 
	  APPROVED, 
	  REJECTED, 
	  ACTIVE	  
}
