package com.service.enums;

public enum ProfileStatus {
	  PENDING_PROFILE_INFO,
	  PENDING_ADDRESS_VERIFICATION,
	  PENDING_ID_VERIFICATION, 
	  PENDING_BACKGROUND_CHECK, 
	  PENDING_DOCUMENT_UPLOAD, 
	  PENDING_TERMS_ACCEPTANCE, 
	  PENDING_REVIEW,
	  REQUIRES_CHANGES,
	  APPROVED, 
	  REJECTED, 
	  ACTIVE	  
}
